platform :ios, '13.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

flutter_root = ENV['FLUTTER_ROOT']
if flutter_root.nil? || flutter_root.empty?
  flutter_bin = `which flutter`.strip
  if flutter_bin && !flutter_bin.empty?
    begin
      flutter_bin = File.realpath(flutter_bin)
    rescue
    end
    flutter_root = File.expand_path('..', File.dirname(flutter_bin))
  end
end
raise 'FLUTTER_ROOT not set and could not be resolved.' if flutter_root.nil? || flutter_root.empty?
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
